### ISSUE TITLE
Doesn't work with modern babel 7

### ISSUE THREAD

**Issue by xamgore** [andreypopp/memoize-decorator#6]
Hi! Tried to use your package, got the following error:

```js
/home/mi/lenin/news-parser/node_modules/memoize-decorator/lib/index.js:16
  if (typeof descriptor.value === 'function') {
                        ^

TypeError: Cannot read property 'value' of undefined
    at memoize (/home/mi/lenin/news-parser/node_modules/memoize-decorator/lib/index.js:16:25)
    at Object.decorateElement (/home/mi/lenin/news-parser/tests/keka.js:9:2704)
    at Object.<anonymous> (/home/mi/lenin/news-parser/tests/keka.js:9:1594)
    at Array.forEach (<anonymous>)
    at Object.decorateClass (/home/mi/lenin/news-parser/tests/keka.js:9:1467)
    at _decorate (/home/mi/lenin/news-parser/tests/keka.js:7:308)
    at Object.<anonymous> (/home/mi/lenin/news-parser/tests/keka.js:35:9)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Module._compile (/home/mi/lenin/news-parser/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:827:10)
```

<details>
Code:

```js
import memoize from 'memoize-decorator'

class A {
  @memoize
  test() {
    console.log('heavy computation')
    return 42
  }
}

let a = new A()
a.test() // prints 'heavy computations', returns 42
a.test() // just returns 42
```

**.babelrc**

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "current"
        }
      }
    ]
  ],
  "plugins": [
    "transform-numeric-separator",
    ["@babel/plugin-proposal-decorators", { "decoratorsBeforeExport": true }],
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-optional-chaining",
    "@babel/plugin-proposal-export-default-from",
    "@babel/plugin-proposal-export-namespace-from"
  ]
}
```

How I ran it:

```node -r @babel/register test.js```

or via

```babel-node test.js```

---

More debugging:

```js
function memoize(target, name, descriptor) {
  console.log('target:', target)
  console.log('name:', name)
  console.log('descriptor:', descriptor)
  ...
}
```

Result:

```js
target: Object [Descriptor] {
  kind: 'method',
  key: 'test',
  placement: 'prototype',
  descriptor:
   { value: [Function: test],
     writable: true,
     configurable: true,
     enumerable: false } }
name: undefined
descriptor: undefined
/home/mi/lenin/news-parser/node_modules/memoize-decorator/lib/index.js:19
  if (typeof descriptor.value === 'function') {
                        ^
```

</details>

**Comment by andreypopp** [comment]
I don't think this package is compatible with new babel decorators transform. This package is also unmaintained so I don't recommend using it at all.
